[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sphinx_template"
version = "0.1.0"
description = "A Sphinx template for documentation."
authors = [{ name = "Your Name", email = "your.email@example.com" }]
license = { text = "MIT" }
readme = "README.md"
keywords = ["sphinx", "template", "documentation"]

dependencies = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-copybutton",
    "sphinx-last-updated-by-git",
    "sphinx-rtd-dark-mode",
    "myst-parser"
]